### ISSUE TITLE
Bug with segment.to_a

### ISSUE THREAD

**Issue by henrytseng** [alivecor/simple_hl7#10]
Using reduce in `.to_a` method in composite seems to produce some `nil` scattered through out the array?

**Comment by hportlock** [comment]
Hi, so right now any empty segments are being returned as `nil` when `.to_a` is called. This is the same behavior for `.map` and `.each`.  What behavior were you expecting?

I suppose it might be somewhat inconsistent with `[]` operator, which creates new subcomposites for empty segments.

**Comment by henrytseng** [comment]
Yes, but there are additional nil values in there for segments that don't
exist AND not just for empty values.

**Comment by hportlock** [comment]
Oh interesting, that does sound strange. Could you post a code sample that shows the problem?

**Comment by hportlock** [comment]
@henrytseng are you still running into this problem?

**Comment by henrytseng** [comment]
I haven't tried to reproduce it since.  I've had a number of other
projects.  I just did some simple string parsing to get around the issue.

**Comment by hportlock** [comment]
Ok, I'll close this for now. Feel free to reopen if you are able to reproduce it in the future.
