### ISSUE TITLE
Parsing through a range of multiple values in a segment?

### ISSUE THREAD

**Issue by bradbajuz** [alivecor/simple_hl7#5]
I'm wondering if there is an easier way to grab multiple values from a segment?

**Example:**
`msg.pid[5].to_s`
**Output:** Gives us patient last name

`msg.pid[5][2].to_s`
**Output:** Gives us patient first name

`order = "#{msg.pid[5].to_s}, #{msg.pid[5][2].to_s}"`
**Output:** Gives us full patient name

But is there an easier way to get the full patient name by iterating?

What about a segment range?
**Example:**

`msg.pid[1..13].to_s`
**Output:** would give the all the data from the PID segment

**Comment by hportlock** [comment]
Hi there! Something like:
```ruby
msg.pid[5].r(1).map {|sc| sc.to_s}
```
Would give you all the components of the patient's name as an array. Is that what you're looking for?

**Comment by bradbajuz** [comment]
This solution will work. I'll still need to process it so it doesn't show brackets, quotation marks and commas.

What about getting the whole PID segment in an array, for example, elements 1 - 13?

Thanks for your help.

**Comment by hportlock** [comment]
If you just want to get a string separated by spaces from the array you could just use `join`:

```ruby
msg.pid[5].r(1).map {|sc| sc.to_s}.join(' ')
```

Offhand I can't think of a simple way to get every element of the PID segment in an array. If you do:

```ruby
msg.pid.map {|sc| sc.to_s}
```

It would give you an array, but it would only include the first subcomponent of each field. In order to get an array containing all the subcomponents you'd probably have to write a more complex loop.

**Comment by bradbajuz** [comment]
I'll have to play with it. Wasn't sure if there was a built in method in the parser. If I figure out a decent loop, I can fork the project and do a pull request for an addition to the README if you want?

**Comment by hportlock** [comment]
Sure if you come up with something good feel free to add it to the README and send a pull request. For now I'll make this issue as closed.
